version: "3.8"

services:
  frontend:
    build:
      context: ./kuyua-fe
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:4000
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./kuyua-be
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
